FLASK_APP=app.app:app
FLASK_ENV=development
FLASK_DEBUG=1

SECRET_KEY=supersecretkey

SQLALCHEMY_DATABASE_URI=sqlite:///../instance/nettools.db
SQLALCHEMY_TRACK_MODIFICATIONS=False

MIGRATIONS_ENABLED=0