"""Initial migration

Revision ID: 06dc18066be6
Revises: 
Create Date: 2025-11-01 23:15:13.697163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '06dc18066be6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('host',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('params',
               existing_type=sa.VARCHAR(length=256),
               type_=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
        batch_op.alter_column('output',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('output',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
        batch_op.alter_column('params',
               existing_type=sqlite.JSON(),
               type_=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('host',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
